# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
 
stages:
- stage: Build  
  jobs:
  - job: job1
    steps:
    - script: echo Build!
      displayName: 'Run a one-line script'

    - script: |
       echo Add other tasks to build, test, and deploy your project.
       echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

- stage: DevDeploy
  variables:
   environment: Dev
  dependsOn: Build 
  jobs:
  - job: job2
    steps:
    - bash: echo $(environment) deploy!
      displayName: 'Run a one-line script'

- stage: QADeploy
  variables:
   environment: QA
  dependsOn: Build 
  jobs:
  - job: job3
    steps:
    - bash: echo $(environment) deploy!
      displayName: 'Run a one-line script'      
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
  - job: job4
    steps:
    - bash: echo Prod Deploy!
      displayName: 'Run a one-line script'            