# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# strategy:
#  matrix:
#   linux:
#     operatingSystem: 'ubuntu-latest'
#   mac:
#     operatingSystem: 'macos-latest'
    
      
pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Buildjob
        steps:
          - script: echo Do the Build Job
  - stage: DevDeploy
    jobs:
      - deployment: 
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: echo deploy to Dev
  - stage: QAdeploy
    jobs:
      - deployment: 
        environment: QA
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo deploy to QA
